spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      indent_output: true


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: '*'
logging:
  level:
    org.hibernate.type: TRACE
